server:
  port: 9009
spring:
  cloud:
    stream:
      bindings:
        output:
          #producer:
            #useNativeEncoding: true
          destination: sensorsx1
      kafka:
        binder:
          brokers: 192.168.99.100:9092
        stream:
          binder:
            brokers: 192.168.99.100:9092
            configuration:
              schema.registry.url: http://192.168.99.100:8081
              key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
              value.serializer: sample.producer1.FooSerde


