spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.100:9092
      bindings:
        output:
          contentType: application/*+avro
          destination: sensor-topic
      schemaRegistryClient:
        endpoint: http://localhost:8081
      schema:
        avro:
          schema-locations: classpath:avro/sensor.avsc
server:
  port: 9109